# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0002_auto_20170711_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='OldPerson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elder.OldPerson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
