# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0003_auto_20170711_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldperson',
            old_name='lasttname',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='oldperson',
            name='ageRangeMax',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='oldperson',
            name='ageRangeMin',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='oldperson',
            name='birthdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='oldperson',
            name='height',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='oldperson',
            name='weight',
            field=models.IntegerField(default=150),
        ),
    ]
