# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elder', '0004_auto_20170713_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldperson',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='oldperson',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='oldperson',
            name='login',
        ),
        migrations.RemoveField(
            model_name='oldperson',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='oldperson',
            name='password',
        ),
        migrations.AddField(
            model_name='oldperson',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
