# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0005_auto_20170714_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oldperson',
            name='height',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='oldperson',
            name='weight',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
