# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0008_auto_20170717_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('OK', 'Matching'), ('KO', 'No Matching'), ('NO_RESPONSE', 'No response')], default='NO_RESPONSE', max_length=15)),
                ('oldperson1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldperson', to='elder.OldPerson')),
                ('oldperson2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldperson_tomatch', to='elder.OldPerson')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='history',
            name='OldPerson',
        ),
        migrations.RemoveField(
            model_name='oldpersonanswers',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='oldpersonanswers',
            name='oldPerson',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='OldPersonAnswers',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
