# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0009_auto_20170717_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldperson',
            name='birthdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
