# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 13:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elder', '0011_auto_20170718_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldperson',
            name='birthday',
            field=models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0), verbose_name='Birthday'),
        ),
    ]
